### ISSUE TITLE
Does not work as expected

### ISSUE THREAD

**Issue by MachariaK** [beyondcode/windy-community#29]
I am using Windy on https://startbootstrap.com/previews/new-age but it's not working. There is no element highlighting.

**Comment by mechelon** [comment]
That's because the whole content on this page is embedded in an iFrame. If you open up the iFrame by itself (https://startbootstrap.github.io/startbootstrap-new-age/), it works as expected: 

![CleanShot 2022-01-21 at 10 44 08@2x](https://user-images.githubusercontent.com/26432041/150504544-79dd178b-b715-45ab-9249-f567e7f753ae.png)

**Comment by MachariaK** [comment]
Yes! Works now.
