### ISSUE TITLE
Extract entire page

### ISSUE THREAD

**Issue by cao-minh-duc** [beyondcode/windy-community#6]
It would be nice if windy can extract and copy entire page

**Comment by Erth0** [comment]
This one would be the perfect one if not all the entire page at least a block of elements for example if there is a card with content inside and you hover over the card it doesn't get only the card styles but the styles from all the elements inside.

**Comment by intrepidws** [comment]
Agreed this would be a huge help.

**Comment by sschlein** [comment]
@Erth0 it should do that if you copy the element... do you have an example where it doesn't work?

You can try copying the body tag via the developer tools window but it might be slow or even freeze due to the amount of computation. We want to improve this in the future but this might take some iterations.

**Comment by mpociot** [comment]
![image](https://user-images.githubusercontent.com/804684/101917205-45792f80-3bc8-11eb-9854-9c148102201b.png)

As @sschlein said - you can extract entire pages using the element inspector. Choose the `body` tag, go to the "Windy" tab and copy it to the clipboard.
