### ISSUE TITLE
Sites that Freeze Windy

### ISSUE THREAD

**Issue by intrepidws** [beyondcode/windy-community#7]
For quite a few sites that I have attempted to use Windy on, it either immediately or very quickly freezes. A list of the sites, so far:

- https://www.totallytarynsocial.com/
- https://foxtrotbranding.com/
- https://www.houseofdorough.com/

I am using Chrome on Mac and have tested it on both Mojave and Catalina, with the same results.

**Comment by sschlein** [comment]
Hey, all these sites have a ton of classes on the body tag. My current assumption is that this is too much for the current algorithm and we need to add some kind of pre-processing to be able to handle this in the future.

I don't know when this will be available and if these sites are your main reason for your purchase, you can contact support@beyondco.de for a refund and try again in a few months and after a few iterations on Windy :-)

I keep this issue open so that we have some sites for testing.

**Comment by MOKuper** [comment]
chrome becomes unresponsive for me and the page crashes using windy on http://thefoodninja.nl
Errors out with `code 6`.

**Comment by mpociot** [comment]
I just fixed the issues with sites freezing Windy - I'll release an update later today 👍
